---
AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC for when GitHub wants to communicate with AWS.
Resources:

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHub_Actions_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': ['repo:bryantabaird/puzzlify:*']
              StringEqualsIgnoreCase:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
      Policies:
        - PolicyName: OidcSafetyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: OidcSafeties
                Effect: Deny
                Action:
                  - sts:AssumeRole
                Resource: "*"
        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:        
              - Sid: AllowActions
                Effect: Allow
                Action: "*"
                Resource: "*"

  # This is the OIDC provider hookup itself. This tells AWS to delegate authN GitHub
  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - d89e3bd43d5d909b47a18977aa9d5ce36cee184c
      Url: https://token.actions.githubusercontent.com

  VercelRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Vercelb_Actions_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.vercel.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'oidc.vercel.com:sub': ['owner:bryantbaird:project:puzzlify:environment:preview', 'owner:bryantbaird:project:puzzlify:environment:production']
              StringEqualsIgnoreCase:
                'oidc.vercel.com:aud': https://vercel.com/bryantbaird
      Policies:
        - PolicyName: OidcSafetyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: OidcSafeties
                Effect: Deny
                Action:
                  - sts:AssumeRole
                Resource: "*"
        - PolicyName: VercelRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowActions
                Effect: Allow
                Action: "*"
                Resource: "*"

  VercelOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - https://vercel.com/bryantbaird
      ThumbprintList:
        - 696db3af0dffc17e65c6a20d925c5a7bd24dec7e
      Url: https://oidc.vercel.com